# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Form_ui.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(598, 706)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(20, 10, 131, 101))
        self.groupBox.setObjectName("groupBox")
        self.radioButton_3 = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_3.setGeometry(QtCore.QRect(10, 20, 82, 17))
        self.radioButton_3.setObjectName("radioButton_3")
        self.radioButton_4 = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_4.setGeometry(QtCore.QRect(10, 40, 82, 17))
        self.radioButton_4.setObjectName("radioButton_4")
        self.radioButton_5 = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_5.setGeometry(QtCore.QRect(10, 60, 82, 17))
        self.radioButton_5.setObjectName("radioButton_5")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(160, 10, 231, 181))
        self.groupBox_2.setObjectName("groupBox_2")
        self.checkBox_3 = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_3.setGeometry(QtCore.QRect(20, 20, 221, 17))
        self.checkBox_3.setObjectName("checkBox_3")
        self.checkBox_4 = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_4.setGeometry(QtCore.QRect(20, 40, 191, 17))
        self.checkBox_4.setObjectName("checkBox_4")
        self.checkBox_5 = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_5.setGeometry(QtCore.QRect(20, 60, 191, 17))
        self.checkBox_5.setObjectName("checkBox_5")
        self.checkBox_6 = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_6.setGeometry(QtCore.QRect(20, 80, 191, 17))
        self.checkBox_6.setObjectName("checkBox_6")
        self.checkBox_7 = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_7.setGeometry(QtCore.QRect(20, 100, 191, 17))
        self.checkBox_7.setObjectName("checkBox_7")
        self.checkBox_8 = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_8.setGeometry(QtCore.QRect(20, 120, 191, 17))
        self.checkBox_8.setObjectName("checkBox_8")
        self.checkBox_9 = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_9.setGeometry(QtCore.QRect(20, 140, 191, 17))
        self.checkBox_9.setObjectName("checkBox_9")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(19, 120, 131, 71))
        self.groupBox_3.setObjectName("groupBox_3")
        self.dateTimeEdit = QtWidgets.QDateTimeEdit(self.groupBox_3)
        self.dateTimeEdit.setGeometry(QtCore.QRect(10, 30, 111, 22))
        self.dateTimeEdit.setDate(QtCore.QDate(2019, 7, 1))
        self.dateTimeEdit.setCalendarPopup(True)
        self.dateTimeEdit.setObjectName("dateTimeEdit")
        self.groupBox_4 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_4.setGeometry(QtCore.QRect(20, 240, 371, 51))
        self.groupBox_4.setObjectName("groupBox_4")
        self.textEdit = QtWidgets.QTextEdit(self.groupBox_4)
        self.textEdit.setEnabled(True)
        self.textEdit.setGeometry(QtCore.QRect(10, 20, 351, 31))
        self.textEdit.setTextInteractionFlags(QtCore.Qt.TextEditorInteraction)
        self.textEdit.setObjectName("textEdit")
        self.groupBox_5 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_5.setGeometry(QtCore.QRect(20, 299, 371, 181))
        self.groupBox_5.setObjectName("groupBox_5")
        self.textEdit_2 = QtWidgets.QTextEdit(self.groupBox_5)
        self.textEdit_2.setGeometry(QtCore.QRect(10, 130, 351, 41))
        self.textEdit_2.setObjectName("textEdit_2")
        self.label = QtWidgets.QLabel(self.groupBox_5)
        self.label.setGeometry(QtCore.QRect(10, 110, 271, 16))
        self.label.setObjectName("label")
        self.radioButton = QtWidgets.QRadioButton(self.groupBox_5)
        self.radioButton.setGeometry(QtCore.QRect(10, 20, 261, 17))
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(self.groupBox_5)
        self.radioButton_2.setGeometry(QtCore.QRect(10, 40, 151, 17))
        self.radioButton_2.setObjectName("radioButton_2")
        self.radioButton_6 = QtWidgets.QRadioButton(self.groupBox_5)
        self.radioButton_6.setGeometry(QtCore.QRect(10, 60, 141, 17))
        self.radioButton_6.setObjectName("radioButton_6")
        self.radioButton_7 = QtWidgets.QRadioButton(self.groupBox_5)
        self.radioButton_7.setGeometry(QtCore.QRect(180, 40, 171, 17))
        self.radioButton_7.setObjectName("radioButton_7")
        self.radioButton_8 = QtWidgets.QRadioButton(self.groupBox_5)
        self.radioButton_8.setGeometry(QtCore.QRect(180, 60, 171, 17))
        self.radioButton_8.setObjectName("radioButton_8")
        self.dateTimeEdit_2 = QtWidgets.QDateTimeEdit(self.groupBox_5)
        self.dateTimeEdit_2.setEnabled(False)
        self.dateTimeEdit_2.setGeometry(QtCore.QRect(210, 80, 111, 22))
        self.dateTimeEdit_2.setDate(QtCore.QDate(2019, 7, 1))
        self.dateTimeEdit_2.setCalendarPopup(True)
        self.dateTimeEdit_2.setObjectName("dateTimeEdit_2")
        self.label_2 = QtWidgets.QLabel(self.groupBox_5)
        self.label_2.setGeometry(QtCore.QRect(10, 80, 191, 16))
        self.label_2.setObjectName("label_2")
        self.groupBox_6 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_6.setGeometry(QtCore.QRect(20, 560, 371, 101))
        self.groupBox_6.setObjectName("groupBox_6")
        self.textEdit_3 = QtWidgets.QTextEdit(self.groupBox_6)
        self.textEdit_3.setGeometry(QtCore.QRect(10, 20, 351, 71))
        self.textEdit_3.setObjectName("textEdit_3")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(20, 480, 110, 31))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(20, 520, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.groupBox_7 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_7.setGeometry(QtCore.QRect(20, 190, 111, 51))
        self.groupBox_7.setObjectName("groupBox_7")
        self.lineEdit = QtWidgets.QLineEdit(self.groupBox_7)
        self.lineEdit.setGeometry(QtCore.QRect(10, 20, 91, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.groupBox_8 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_8.setGeometry(QtCore.QRect(150, 190, 111, 51))
        self.groupBox_8.setObjectName("groupBox_8")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.groupBox_8)
        self.lineEdit_2.setGeometry(QtCore.QRect(10, 20, 91, 20))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.groupBox_9 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_9.setGeometry(QtCore.QRect(280, 190, 111, 51))
        self.groupBox_9.setObjectName("groupBox_9")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.groupBox_9)
        self.lineEdit_3.setGeometry(QtCore.QRect(10, 20, 91, 20))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(150, 480, 110, 31))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setObjectName("pushButton_3")
        self.groupBox_10 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_10.setGeometry(QtCore.QRect(400, 10, 181, 311))
        self.groupBox_10.setObjectName("groupBox_10")
        self.textEdit_4 = QtWidgets.QTextEdit(self.groupBox_10)
        self.textEdit_4.setGeometry(QtCore.QRect(10, 20, 161, 281))
        self.textEdit_4.setTextInteractionFlags(QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.textEdit_4.setObjectName("textEdit_4")
        self.groupBox_11 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_11.setGeometry(QtCore.QRect(400, 330, 181, 301))
        self.groupBox_11.setObjectName("groupBox_11")
        self.textEdit_5 = QtWidgets.QTextEdit(self.groupBox_11)
        self.textEdit_5.setGeometry(QtCore.QRect(10, 20, 161, 271))
        self.textEdit_5.setTextInteractionFlags(QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.textEdit_5.setObjectName("textEdit_5")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(150, 520, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(280, 480, 111, 71))
        self.pushButton_5.setObjectName("pushButton_5")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 598, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Форма заполнения ГП/СИ"))
        self.groupBox.setTitle(_translate("MainWindow", "Сегмент влияние:"))
        self.radioButton_3.setText(_translate("MainWindow", "Физ. Лица"))
        self.radioButton_4.setText(_translate("MainWindow", "Юр. Лица"))
        self.radioButton_5.setText(_translate("MainWindow", "ФЛ + ЮЛ"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Влияние на сервис:"))
        self.checkBox_3.setText(_translate("MainWindow", "Проблемы с BRAS, с авторизацией"))
        self.checkBox_4.setText(_translate("MainWindow", "100% отсутствие мг/мн"))
        self.checkBox_5.setText(_translate("MainWindow", "100% отсутствие СПД"))
        self.checkBox_6.setText(_translate("MainWindow", "100% отсутствие IpTV"))
        self.checkBox_7.setText(_translate("MainWindow", "Ухудшение качества МГ/МН"))
        self.checkBox_8.setText(_translate("MainWindow", "Ухудшение качества СПД"))
        self.checkBox_9.setText(_translate("MainWindow", "Ухудшение качества IpTV"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Дата/Время начала"))
        self.dateTimeEdit.setDisplayFormat(_translate("MainWindow", "HH:mm dd.MM.yyyy"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Место/участок проблемы:"))
        self.textEdit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.groupBox_5.setTitle(_translate("MainWindow", "Причина проблемы:"))
        self.label.setText(_translate("MainWindow", "Другая причина или дополнительная информация:"))
        self.radioButton.setText(_translate("MainWindow", "Сбой в работе оборудования ПАО Ростелеком"))
        self.radioButton_2.setText(_translate("MainWindow", "Линейное повреждение"))
        self.radioButton_6.setText(_translate("MainWindow", "РНР на сети филиала"))
        self.radioButton_7.setText(_translate("MainWindow", "Аварийное отключение Э/Э"))
        self.radioButton_8.setText(_translate("MainWindow", "Плановое отключение Э/Э"))
        self.dateTimeEdit_2.setDisplayFormat(_translate("MainWindow", "HH:mm dd.MM.yyyy"))
        self.label_2.setText(_translate("MainWindow", "Время завершение плановых работ:"))
        self.groupBox_6.setTitle(_translate("MainWindow", "Результат для копирования в ГП/СИ и Рассылки для ЛТП:"))
        self.pushButton.setText(_translate("MainWindow", "Обработать данные"))
        self.pushButton_2.setText(_translate("MainWindow", "Copy for mail"))
        self.groupBox_7.setTitle(_translate("MainWindow", "СИ"))
        self.groupBox_8.setTitle(_translate("MainWindow", "Г П"))
        self.groupBox_9.setTitle(_translate("MainWindow", "ТТ"))
        self.pushButton_3.setText(_translate("MainWindow", "Скопировать адресаты"))
        self.groupBox_10.setTitle(_translate("MainWindow", "Техподдержка/Тематики:"))
        self.groupBox_11.setTitle(_translate("MainWindow", "Адресаты"))
        self.pushButton_4.setText(_translate("MainWindow", "Copy for OSS"))
        self.pushButton_5.setText(_translate("MainWindow", "Обновить шаблон"))

